name: mtr_py39
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py39h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.10.5=py39h06a4308_0
  - cffi=2.0.0=py39h4eded50_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.3=pyhe01879c_0
  - cuda-cccl=12.1.109=0
  - cuda-cccl_linux-64=13.0.85=1
  - cuda-command-line-tools=12.1.1=0
  - cuda-compiler=12.6.2=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cudart-static=13.0.96=h3b4bcfc_1
  - cuda-cudart-static_linux-64=13.0.96=hbe36340_1
  - cuda-culibos-static=13.0.85=h3b4bcfc_0
  - cuda-cuobjdump=13.0.85=hf384b4a_0
  - cuda-cupti=12.1.105=0
  - cuda-cuxxfilt=13.0.85=hf384b4a_0
  - cuda-documentation=12.4.127=0
  - cuda-driver-dev=13.0.96=h3b4bcfc_1
  - cuda-driver-dev_linux-64=13.0.96=hbe36340_1
  - cuda-gdb=13.0.85=hf384b4a_0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.6.2=0
  - cuda-libraries-static=13.0.2=0
  - cuda-nsight=13.0.85=h6a26bb4_0
  - cuda-nvcc=12.4.131=0
  - cuda-nvdisasm=13.0.85=hf384b4a_0
  - cuda-nvml-dev=13.0.87=ha2c4e13_0
  - cuda-nvprof=12.4.127=0
  - cuda-nvprune=13.0.85=hf384b4a_0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvrtc-static=13.0.88=h3b4bcfc_0
  - cuda-nvtx=12.1.105=0
  - cuda-nvvp=12.4.127=0
  - cuda-opencl=13.0.85=hf384b4a_0
  - cuda-opencl-dev=13.0.85=h3b4bcfc_0
  - cuda-profiler-api=13.0.85=h6a26bb4_0
  - cuda-runtime=12.1.0=0
  - cuda-sanitizer-api=13.0.85=hf384b4a_0
  - cuda-toolkit=12.1.0=0
  - cuda-tools=12.1.1=0
  - cuda-version=13.0=3
  - cuda-visual-tools=12.6.2=0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.8.16=py39hbdd6827_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.17.0=py39h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gds-tools=1.15.1.6=h2e68323_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py39h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py39h06a4308_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py39h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcublas-static=13.1.0.3=h3b4bcfc_0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcufft-static=12.0.0.61=h3b4bcfc_0
  - libcufile=1.15.1.6=h2e68323_0
  - libcufile-dev=1.15.1.6=h2e68323_0
  - libcufile-static=1.15.1.6=h3b4bcfc_0
  - libcurand=10.4.0.35=h50d9014_0
  - libcurand-dev=10.4.0.35=h50d9014_0
  - libcurand-static=10.4.0.35=h3b4bcfc_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusolver-static=12.0.4.66=h3b4bcfc_0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libcusparse-static=12.6.3.3=h3b4bcfc_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.84.4=h77a78f3_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnpp-static=13.0.1.2=hfdad374_0
  - libnsl=2.0.0=h5eee18b_0
  - libnvfatbin=13.0.85=hf384b4a_0
  - libnvfatbin-dev=13.0.85=hf384b4a_0
  - libnvfatbin-static=13.0.85=h3b4bcfc_0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjitlink-static=13.0.88=h3b4bcfc_0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libnvjpeg-static=13.0.1.86=0
  - libnvvm-samples=12.1.105=0
  - libopenjpeg=2.5.4=hee96239_0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py39h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_2
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py39h06a4308_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - nsight-compute=2025.3.1.4=hcd14d4a_0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.4=h4e0627c_0
  - openssl=3.0.18=hd6dcaed_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py39h06a4308_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.24=h0dcde21_1
  - pytorch=2.5.1=py3.9_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py39h5eee18b_0
  - pyzmq=27.1.0=py39hcf8288c_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py39h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=2.5.1=py39_cu121
  - torchtriton=3.1.0=py39
  - torchvision=0.20.1=py39_cu121
  - tornado=6.5.1=py39h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py39h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py39h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==1.4.0
      - array-record==0.5.1
      - astunparse==1.6.3
      - cachetools==5.5.2
      - clang==5.0
      - click==8.1.8
      - cloudpickle==3.1.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - dacite==1.8.1
      - dask==2023.3.1
      - dataclass-array==1.5.1
      - dm-tree==0.1.8
      - easydict==1.13
      - einops==0.8.1
      - einsum==0.3.0
      - etils==1.5.2
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gast==0.4.0
      - google-auth==2.16.2
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.1.0
      - imageio==2.37.2
      - immutabledict==2.2.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jax==0.4.13
      - jaxlib==0.4.13
      - joblib==1.5.2
      - keras==2.13.1
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.7
      - lark==1.3.1
      - lazy-loader==0.4
      - libclang==18.1.1
      - locket==1.0.0
      - markdown==3.9
      - matplotlib==3.6.1
      - ml-dtypes==0.5.3
      - motiontransformer==0.1.0+e6e079c
      - narwhals==2.10.0
      - numpy==1.23.5
      - oauthlib==3.3.1
      - openexr==3.4.2
      - opt-einsum==3.3.0
      - packaging==25.0
      - pandas==1.5.3
      - partd==1.4.2
      - pillow==9.2.0
      - plotly==5.13.1
      - promise==2.3
      - protobuf==3.20.3
      - psutil==7.1.2
      - pyarrow==16.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.6.0
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-image==0.20.0
      - scikit-learn==1.2.2
      - scipy==1.9.1
      - setuptools==67.6.0
      - six==1.15.0
      - tenacity==9.1.2
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensorflow==2.13.0
      - tensorflow-addons==0.23.0
      - tensorflow-datasets==4.9.3
      - tensorflow-estimator==2.13.0
      - tensorflow-graphics==2021.12.3
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.17.2
      - tensorflow-probability==0.21.0
      - termcolor==1.1.0
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - toml==0.10.2
      - toolz==1.1.0
      - tqdm==4.67.1
      - trimesh==4.2.0
      - typeguard==2.13.3
      - typing-extensions==4.5.0
      - visu3d==1.5.1
      - waymo-open-dataset-tf-2-12-0==1.6.7
      - werkzeug==3.1.3
      - wrapt==1.12.1
      - zipp==3.23.0
prefix: /home/atharva/.conda/envs/mtr_py39
